[package]
name = "newton"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = "3.1.1"
raster = "0.2.0"
num = "0.4.0"
rand = "0.8.5"